exchange/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

app_name = 'exchange'

router = DefaultRouter()
router.register(r'skills', SkillViewSet)
router.register(r'exchanges', ExchangeRequestViewSet)

urlpatterns = [
    # path('', include(router.urls)),
    # path('', index, name='home'),
    path('', index, name='index'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    # path('logout/', views.logout_view, name='logout'),

    path('profile/', profile, name='profile'),
    path('skill_search/', skill_search, name='skill_search'),
    path('send_exchange_request/', send_exchange_request, name='send_exchange_request'),
    path('send_feedback/', send_feedback, name='send_feedback'),
    path('create_course/', create_course.as_view(), name='create_course'),  # Use CreateCourse as a class-based view
    path('course_list/', course_list, name='course_list'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),

    # path('', redirect_to_index),
]

skill_exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exchange.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

templates/about.html
{% extends 'base.html' %}

{% block title %}О нас{% endblock %}

{% block content %}
  <h2>О нас</h2>
  <p>Наша платформа предоставляет возможность обмениваться навыками и услугами между пользователями.</p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Skill Exchange{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Наш собственный CSS -->
    <link rel="stylesheet" href="{% static 'static/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Skill Exchange</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Главная <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/course_list/">Список курсов</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about/">О нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact/">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/create_course/">Создать курс</a>
                </li>
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'exchange:skill_search' %}">Поиск курсов</a>
            </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/profile/">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout/">Выход</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login/">Вход</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/register/">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'footer.html' %}


    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}
  <h2>Контакты</h2>
  <p>Свяжитесь с нами по электронной почте: example@example.com</p>
{% endblock %}

templates/course_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h2 class="mt-4 mb-4">Список курсов</h2>
    <div class="row">
      {% for course in courses %}
      <div class="col-md-4 mb-4">
        <div class="card">
          {% if course.image %}
          <img src="{{ course.image.url }}" class="card-img-top" alt="{{ course.title }}">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ course.title }}</h5>
            <p class="card-text">{{ course.description }}</p>
            <a href="#" class="btn btn-primary">Перейти к курсу</a>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-md-12">
        <p>Нет доступных курсов</p>
      </div>
      {% endfor %}
    </div>
    {% if courses.has_other_pages %}
    <ul class="pagination">
      {% if courses.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ courses.previous_page_number }}">{{ courses.previous_page_number }}</a></li>
      {% endif %}
      <li class="page-item active"><a class="page-link" href="?page={{ courses.number }}">{{ courses.number }}</a></li>
      {% if courses.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ courses.next_page_number }}">{{ courses.next_page_number }}</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ courses.paginator.num_pages }}">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}
  </div>
{% endblock %}

templates/create_course.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Добавление курса{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    {% bootstrap_messages %}

                    <h2 class="card-title mb-4 text-center">Добавление курса</h2>

                    <form method="post" enctype="multipart/form-data" style="display: flex; flex-direction: column;">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.title.label_tag }}
                            {{ form.title }}
                            {{ form.title.errors }}
                        </div>

                        <div class="form-group">
                            {{ form.description.label_tag }}
                            {{ form.description }}
                            {{ form.description.errors }}
                        </div>

                        <div class="form-group">
                            {{ form.image.label_tag }}
                            {{ form.image }}
                            {{ form.image.errors }}
                        </div>

                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'footer.css' %}">
</head>
<body>
    <footer class="footer">
  <video class="footer_video" muted="" loop="" autoplay src="//cdn.shopify.com/s/files/1/0526/6905/5172/t/5/assets/footer.mp4?v=29581141968431347981633714450" type="video/mp4">
  </video>

  <div class="container">
    <div class="footer_inner">
      <div class="c-footer">
        <div class="layout">
          <div class="layout_item w-50">
            <div class="newsletter">
              <h3 class="newsletter_title">Get updates on fun stuff you probably want to know about in your inbox.</h3>
              <form action="">
                <input type="text" placeholder="Email Address">
                <button>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z" />
                  </svg>
                </button>
              </form>
            </div>
          </div>

          <div class="layout_item w-25">
            <nav class="c-nav-tool">
              <h4 class="c-nav-tool_title">Menu</h4>
              <ul class="c-nav-tool_list">
                <li>
                  <a href="/collections/all" class="c-link">Shop All</a>
                </li>

                <li>
                  <a href="/pages/about-us" class="c-link">About Us</a>
                </li>

                <li>
                  <a href="/blogs/community" class="c-link">Community</a>
                </li>
                <li>
                  <a href="#" class="c-link">Vibes</a>
                </li>
              </ul>
            </nav>

          </div>

          <div class="layout_item w-25">
            <nav class="c-nav-tool">
              <h4 class="c-nav-tool_title">Support</h4>
              <ul class="c-nav-tool_list">

                <li class="c-nav-tool_item">
                  <a href="/pages/shipping-returns" class="c-link">Shipping &amp; Returns</a>
                </li>

                <li class="c-nav-tool_item">
                  <a href="/pages/help" class="c-link">Help &amp; FAQ</a>
                </li>

                <li class="c-nav-tool_item">
                  <a href="/pages/terms-conditions" class="c-link">Terms &amp; Conditions</a>
                </li>

                <li class="c-nav-tool_item">
                  <a href="/pages/privacy-policy" class="c-link">Privacy Policy</a>
                </li>

                <li class="c-nav-tool_item">
                  <a href="/pages/contact" class="c-link">Contact</a>
                </li>

                <li class="c-nav-tool_item">
                  <a href="/account/login" class="c-link">
                    Login
                  </a>
                </li>
              </ul>
            </nav>

          </div>
        </div>
        <div class="layout c-2">
          <div class="layout_item w-50">
            <ul class="flex">
              <li>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path d="M12 6.654a6.786 6.786 0 0 1 2.596 5.344A6.786 6.786 0 0 1 12 17.34a6.786 6.786 0 0 1-2.596-5.343A6.786 6.786 0 0 1 12 6.654zm-.87-.582A7.783 7.783 0 0 0 8.4 12a7.783 7.783 0 0 0 2.728 5.926 6.798 6.798 0 1 1 .003-11.854zm1.742 11.854A7.783 7.783 0 0 0 15.6 12a7.783 7.783 0 0 0-2.73-5.928 6.798 6.798 0 1 1 .003 11.854z" />
                </svg>
              </li>
              <li>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path d="M1 4h22v2H1V4zm0 14h22v2H1v-2zm18.622-3.086l-.174-.87h-1.949l-.31.863-1.562.003c1.005-2.406 1.75-4.19 2.236-5.348.127-.303.353-.457.685-.455.254.002.669.002 1.245 0L21 14.912l-1.378.003zm-1.684-2.062h1.256l-.47-2.18-.786 2.18zM7.872 9.106l1.57.002-2.427 5.806-1.59-.001c-.537-2.07-.932-3.606-1.184-4.605-.077-.307-.23-.521-.526-.622-.263-.09-.701-.23-1.315-.419v-.16h2.509c.434 0 .687.21.769.64l.62 3.289 1.574-3.93zm3.727.002l-1.24 5.805-1.495-.002 1.24-5.805 1.495.002zM14.631 9c.446 0 1.01.138 1.334.267l-.262 1.204c-.293-.118-.775-.277-1.18-.27-.59.009-.954.256-.954.493 0 .384.632.578 1.284.999.743.48.84.91.831 1.378-.01.971-.831 1.929-2.564 1.929-.791-.012-1.076-.078-1.72-.306l.272-1.256c.656.274.935.361 1.495.361.515 0 .956-.207.96-.568.002-.257-.155-.384-.732-.702-.577-.317-1.385-.756-1.375-1.64C12.033 9.759 13.107 9 14.63 9z" />
                </svg>
              </li>
              <li>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path d="M15 17a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15zM2 2h4v20H2V2z" />
                </svg>
              </li>
              <li>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm-1-6v2h2v-2h1a2.5 2.5 0 0 0 2-4 2.5 2.5 0 0 0-2-4h-1V6h-2v2H8v8h3zm-1-3h4a.5.5 0 1 1 0 1h-4v-1zm0-3h4a.5.5 0 1 1 0 1h-4v-1z" />
                </svg>
              </li>
              <li>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path d="M20.067 8.478c.492.88.556 2.014.3 3.327-.74 3.806-3.276 5.12-6.514 5.12h-.5a.805.805 0 0 0-.794.68l-.04.22-.63 3.993-.032.17a.804.804 0 0 1-.794.679H7.72a.483.483 0 0 1-.477-.558L7.418 21h1.518l.95-6.02h1.385c4.678 0 7.75-2.203 8.796-6.502zm-2.96-5.09c.762.868.983 1.81.752 3.285-.019.123-.04.24-.062.36-.735 3.773-3.089 5.446-6.956 5.446H8.957c-.63 0-1.174.414-1.354 1.002l-.014-.002-.93 5.894H3.121a.051.051 0 0 1-.05-.06l2.598-16.51A.95.95 0 0 1 6.607 2h5.976c2.183 0 3.716.469 4.523 1.388z" />
                </svg>
              </li>
            </ul>
          </div>
          <div class="layout_item w-25">
            <ul class="flex">
              <li>
                <a href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path d="M12 2C6.477 2 2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.879V14.89h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.989C18.343 21.129 22 16.99 22 12c0-5.523-4.477-10-10-10z" />
                  </svg>
                </a>
              </li>
              <li>
                <a href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path d="M22.162 5.656a8.384 8.384 0 0 1-2.402.658A4.196 4.196 0 0 0 21.6 4c-.82.488-1.719.83-2.656 1.015a4.182 4.182 0 0 0-7.126 3.814 11.874 11.874 0 0 1-8.62-4.37 4.168 4.168 0 0 0-.566 2.103c0 1.45.738 2.731 1.86 3.481a4.168 4.168 0 0 1-1.894-.523v.052a4.185 4.185 0 0 0 3.355 4.101 4.21 4.21 0 0 1-1.89.072A4.185 4.185 0 0 0 7.97 16.65a8.394 8.394 0 0 1-6.191 1.732 11.83 11.83 0 0 0 6.41 1.88c7.693 0 11.9-6.373 11.9-11.9 0-.18-.005-.362-.013-.54a8.496 8.496 0 0 0 2.087-2.165z" />
                  </svg>
                </a>
              </li>
              <li>
                <a href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path d="M12 2c2.717 0 3.056.01 4.122.06 1.065.05 1.79.217 2.428.465.66.254 1.216.598 1.772 1.153a4.908 4.908 0 0 1 1.153 1.772c.247.637.415 1.363.465 2.428.047 1.066.06 1.405.06 4.122 0 2.717-.01 3.056-.06 4.122-.05 1.065-.218 1.79-.465 2.428a4.883 4.883 0 0 1-1.153 1.772 4.915 4.915 0 0 1-1.772 1.153c-.637.247-1.363.415-2.428.465-1.066.047-1.405.06-4.122.06-2.717 0-3.056-.01-4.122-.06-1.065-.05-1.79-.218-2.428-.465a4.89 4.89 0 0 1-1.772-1.153 4.904 4.904 0 0 1-1.153-1.772c-.248-.637-.415-1.363-.465-2.428C2.013 15.056 2 14.717 2 12c0-2.717.01-3.056.06-4.122.05-1.066.217-1.79.465-2.428a4.88 4.88 0 0 1 1.153-1.772A4.897 4.897 0 0 1 5.45 2.525c.638-.248 1.362-.415 2.428-.465C8.944 2.013 9.283 2 12 2zm0 5a5 5 0 1 0 0 10 5 5 0 0 0 0-10zm6.5-.25a1.25 1.25 0 0 0-2.5 0 1.25 1.25 0 0 0 2.5 0zM12 9a3 3 0 1 1 0 6 3 3 0 0 1 0-6z" />
                  </svg>
                </a>
              </li>
            </ul>
          </div>
          <div class="layout_item w-25" style="display:flex;justify-content: end;align-items: center;">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="36" height="36">
              <path fill="none" d="M0 0h24v24H0z" />
              <path d="M12 2c5.52 0 10 4.48 10 10s-4.48 10-10 10S2 17.52 2 12 6.48 2 12 2zm1 10h3l-4-4-4 4h3v4h2v-4z" />
            </svg>
          </div>
        </div>
      </div>
    </div>
    <div class="footer_copyright">
      <p>&copy; 2022 The Afterlogo Company Inc.</p>
    </div>
  </div>
</footer>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">Добро пожаловать на Skill Exchange!</h1>
    <p class="lead">Обменивайтесь навыками и услугами с другими пользователями.</p>
    <hr class="my-4">
    <p>Выберите курс, который соответствует вашим интересам и начните обмениваться!</p>
    <a class="btn btn-primary btn-lg" href="/course_list/" role="button">Список курсов</a>
  </div>

  <div class="row">
    <!-- Карточки курсов, предметов и рейтинга -->
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Курсы по предметам</h5>
          <p class="card-text">Выберите курс по интересующему вас предмету.</p>
          <a href="#" class="btn btn-primary">Просмотреть курсы</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Курсы по рейтингу</h5>
          <p class="card-text">Выберите популярные курсы с высоким рейтингом.</p>
          <a href="#" class="btn btn-primary">Просмотреть курсы</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}


{% block title %} Профиль пользователя {% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
    <p>Здравствуйте! {{ user.first_name }} {{ user.last_name }}</p>
    {% else %}
        <p>Здравствуйте</p>
        </form>
    {% endif %}
    <h3>Ваши обьявление</h3>

{% endblock %}

templates/send_exchange_request.html
{% extends 'base.html' %}

{% block content %}
  <h2>Отправить запрос на обмен</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить запрос</button>
  </form>
{% endblock %}

templates/send_feedback.html
{% extends 'base.html' %}

{% block content %}
  <h2>Отправить обратную связь</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить обратную связь</button>
  </form>
{% endblock %}

templates/skill_search.html
{% extends 'base.html' %}


{% block search %}
  <h2>Поиск курсов</h2>
  <form method="get">
    <input type="text" name="q" placeholder="Введите запрос">
    <button type="submit">Искать</button>
  </form>

  <h3>Найденные курсы:</h3>
  <ul>
    {% for course in courses %}
      <li>{{ course.title }}</li>
    {% empty %}
      <li>Ничего не найдено</li>
    {% endfor %}
  </ul>
{% endblock %}